/* soapServer.c
   Generated by gSOAP 2.8.123 for ./event.h

gSOAP XML Web services tools
Copyright (C) 2000-2021, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapServer.c ver 2.8.123 2022-11-18 14:59:00 GMT")
SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	soap->keep_alive = soap->max_keep_alive + 1;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->keep_alive > 0 && soap->max_keep_alive > 0)
			soap->keep_alive--;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if ((soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap))) && soap->error && soap->error < SOAP_STOP)
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}
#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	(void)soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "SOAP-ENV:Fault"))
		return soap_serve_SOAP_ENV__Fault(soap);
	if (!soap_match_tag(soap, soap->tag, "tev:PullMessages"))
		return soap_serve___tev__PullMessages(soap);
	if (!soap_match_tag(soap, soap->tag, "tev:Seek"))
		return soap_serve___tev__Seek(soap);
	if (!soap_match_tag(soap, soap->tag, "tev:SetSynchronizationPoint"))
		return soap_serve___tev__SetSynchronizationPoint(soap);
	if (!soap_match_tag(soap, soap->tag, "wsnt:Unsubscribe"))
		return soap_serve___tev__Unsubscribe(soap);
	if (!soap_match_tag(soap, soap->tag, "tev:GetServiceCapabilities"))
		return soap_serve___tev__GetServiceCapabilities(soap);
	if (!soap_match_tag(soap, soap->tag, "tev:CreatePullPointSubscription"))
		return soap_serve___tev__CreatePullPointSubscription(soap);
	if (!soap_match_tag(soap, soap->tag, "tev:GetEventProperties"))
		return soap_serve___tev__GetEventProperties(soap);
	if (!soap_match_tag(soap, soap->tag, "tev:AddEventBroker"))
		return soap_serve___tev__AddEventBroker(soap);
	if (!soap_match_tag(soap, soap->tag, "tev:DeleteEventBroker"))
		return soap_serve___tev__DeleteEventBroker(soap);
	if (!soap_match_tag(soap, soap->tag, "tev:GetEventBrokers"))
		return soap_serve___tev__GetEventBrokers(soap);
	if (!soap_match_tag(soap, soap->tag, "wsnt:Renew"))
		return soap_serve___tev__Renew(soap);
	if (!soap_match_tag(soap, soap->tag, "wsnt:Unsubscribe"))
		return soap_serve___tev__Unsubscribe_(soap);
	if (!soap_match_tag(soap, soap->tag, "wsnt:Subscribe"))
		return soap_serve___tev__Subscribe(soap);
	if (!soap_match_tag(soap, soap->tag, "wsnt:GetCurrentMessage"))
		return soap_serve___tev__GetCurrentMessage(soap);
	if (!soap_match_tag(soap, soap->tag, "wsnt:Notify"))
		return soap_serve___tev__Notify(soap);
	if (!soap_match_tag(soap, soap->tag, "wsnt:GetMessages"))
		return soap_serve___tev__GetMessages(soap);
	if (!soap_match_tag(soap, soap->tag, "wsnt:DestroyPullPoint"))
		return soap_serve___tev__DestroyPullPoint(soap);
	if (!soap_match_tag(soap, soap->tag, "wsnt:Notify"))
		return soap_serve___tev__Notify_(soap);
	if (!soap_match_tag(soap, soap->tag, "wsnt:CreatePullPoint"))
		return soap_serve___tev__CreatePullPoint(soap);
	if (!soap_match_tag(soap, soap->tag, "wsnt:Renew"))
		return soap_serve___tev__Renew_(soap);
	if (!soap_match_tag(soap, soap->tag, "wsnt:Unsubscribe"))
		return soap_serve___tev__Unsubscribe__(soap);
	if (!soap_match_tag(soap, soap->tag, "wsnt:PauseSubscription"))
		return soap_serve___tev__PauseSubscription(soap);
	if (!soap_match_tag(soap, soap->tag, "wsnt:ResumeSubscription"))
		return soap_serve___tev__ResumeSubscription(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_SOAP_ENV__Fault(struct soap *soap)
{	struct SOAP_ENV__Fault soap_tmp_SOAP_ENV__Fault;
	soap_default_SOAP_ENV__Fault(soap, &soap_tmp_SOAP_ENV__Fault);
	if (!soap_get_SOAP_ENV__Fault(soap, &soap_tmp_SOAP_ENV__Fault, "SOAP-ENV:Fault", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = SOAP_ENV__Fault(soap, soap_tmp_SOAP_ENV__Fault.faultcode, soap_tmp_SOAP_ENV__Fault.faultstring, soap_tmp_SOAP_ENV__Fault.faultactor, soap_tmp_SOAP_ENV__Fault.detail, soap_tmp_SOAP_ENV__Fault.SOAP_ENV__Code, soap_tmp_SOAP_ENV__Fault.SOAP_ENV__Reason, soap_tmp_SOAP_ENV__Fault.SOAP_ENV__Node, soap_tmp_SOAP_ENV__Fault.SOAP_ENV__Role, soap_tmp_SOAP_ENV__Fault.SOAP_ENV__Detail);
	if (soap->error)
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tev__PullMessages(struct soap *soap)
{	struct __tev__PullMessages soap_tmp___tev__PullMessages;
	struct _tev__PullMessagesResponse tev__PullMessagesResponse;
	soap_default__tev__PullMessagesResponse(soap, &tev__PullMessagesResponse);
	soap_default___tev__PullMessages(soap, &soap_tmp___tev__PullMessages);
	if (!soap_get___tev__PullMessages(soap, &soap_tmp___tev__PullMessages, "-tev:PullMessages", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tev__PullMessages(soap, soap_tmp___tev__PullMessages.tev__PullMessages, &tev__PullMessagesResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize__tev__PullMessagesResponse(soap, &tev__PullMessagesResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__tev__PullMessagesResponse(soap, &tev__PullMessagesResponse, "tev:PullMessagesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__tev__PullMessagesResponse(soap, &tev__PullMessagesResponse, "tev:PullMessagesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tev__Seek(struct soap *soap)
{	struct __tev__Seek soap_tmp___tev__Seek;
	struct _tev__SeekResponse tev__SeekResponse;
	soap_default__tev__SeekResponse(soap, &tev__SeekResponse);
	soap_default___tev__Seek(soap, &soap_tmp___tev__Seek);
	if (!soap_get___tev__Seek(soap, &soap_tmp___tev__Seek, "-tev:Seek", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tev__Seek(soap, soap_tmp___tev__Seek.tev__Seek, &tev__SeekResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize__tev__SeekResponse(soap, &tev__SeekResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__tev__SeekResponse(soap, &tev__SeekResponse, "tev:SeekResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__tev__SeekResponse(soap, &tev__SeekResponse, "tev:SeekResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tev__SetSynchronizationPoint(struct soap *soap)
{	struct __tev__SetSynchronizationPoint soap_tmp___tev__SetSynchronizationPoint;
	struct _tev__SetSynchronizationPointResponse tev__SetSynchronizationPointResponse;
	soap_default__tev__SetSynchronizationPointResponse(soap, &tev__SetSynchronizationPointResponse);
	soap_default___tev__SetSynchronizationPoint(soap, &soap_tmp___tev__SetSynchronizationPoint);
	if (!soap_get___tev__SetSynchronizationPoint(soap, &soap_tmp___tev__SetSynchronizationPoint, "-tev:SetSynchronizationPoint", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tev__SetSynchronizationPoint(soap, soap_tmp___tev__SetSynchronizationPoint.tev__SetSynchronizationPoint, &tev__SetSynchronizationPointResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize__tev__SetSynchronizationPointResponse(soap, &tev__SetSynchronizationPointResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__tev__SetSynchronizationPointResponse(soap, &tev__SetSynchronizationPointResponse, "tev:SetSynchronizationPointResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__tev__SetSynchronizationPointResponse(soap, &tev__SetSynchronizationPointResponse, "tev:SetSynchronizationPointResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tev__Unsubscribe(struct soap *soap)
{	struct __tev__Unsubscribe soap_tmp___tev__Unsubscribe;
	struct _wsnt__UnsubscribeResponse wsnt__UnsubscribeResponse;
	soap_default__wsnt__UnsubscribeResponse(soap, &wsnt__UnsubscribeResponse);
	soap_default___tev__Unsubscribe(soap, &soap_tmp___tev__Unsubscribe);
	if (!soap_get___tev__Unsubscribe(soap, &soap_tmp___tev__Unsubscribe, "-tev:Unsubscribe", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tev__Unsubscribe(soap, soap_tmp___tev__Unsubscribe.wsnt__Unsubscribe, &wsnt__UnsubscribeResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize__wsnt__UnsubscribeResponse(soap, &wsnt__UnsubscribeResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__wsnt__UnsubscribeResponse(soap, &wsnt__UnsubscribeResponse, "wsnt:UnsubscribeResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__wsnt__UnsubscribeResponse(soap, &wsnt__UnsubscribeResponse, "wsnt:UnsubscribeResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tev__GetServiceCapabilities(struct soap *soap)
{	struct __tev__GetServiceCapabilities soap_tmp___tev__GetServiceCapabilities;
	struct _tev__GetServiceCapabilitiesResponse tev__GetServiceCapabilitiesResponse;
	soap_default__tev__GetServiceCapabilitiesResponse(soap, &tev__GetServiceCapabilitiesResponse);
	soap_default___tev__GetServiceCapabilities(soap, &soap_tmp___tev__GetServiceCapabilities);
	if (!soap_get___tev__GetServiceCapabilities(soap, &soap_tmp___tev__GetServiceCapabilities, "-tev:GetServiceCapabilities", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tev__GetServiceCapabilities(soap, soap_tmp___tev__GetServiceCapabilities.tev__GetServiceCapabilities, &tev__GetServiceCapabilitiesResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize__tev__GetServiceCapabilitiesResponse(soap, &tev__GetServiceCapabilitiesResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__tev__GetServiceCapabilitiesResponse(soap, &tev__GetServiceCapabilitiesResponse, "tev:GetServiceCapabilitiesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__tev__GetServiceCapabilitiesResponse(soap, &tev__GetServiceCapabilitiesResponse, "tev:GetServiceCapabilitiesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tev__CreatePullPointSubscription(struct soap *soap)
{	struct __tev__CreatePullPointSubscription soap_tmp___tev__CreatePullPointSubscription;
	struct _tev__CreatePullPointSubscriptionResponse tev__CreatePullPointSubscriptionResponse;
	soap_default__tev__CreatePullPointSubscriptionResponse(soap, &tev__CreatePullPointSubscriptionResponse);
	soap_default___tev__CreatePullPointSubscription(soap, &soap_tmp___tev__CreatePullPointSubscription);
	if (!soap_get___tev__CreatePullPointSubscription(soap, &soap_tmp___tev__CreatePullPointSubscription, "-tev:CreatePullPointSubscription", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tev__CreatePullPointSubscription(soap, soap_tmp___tev__CreatePullPointSubscription.tev__CreatePullPointSubscription, &tev__CreatePullPointSubscriptionResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize__tev__CreatePullPointSubscriptionResponse(soap, &tev__CreatePullPointSubscriptionResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__tev__CreatePullPointSubscriptionResponse(soap, &tev__CreatePullPointSubscriptionResponse, "tev:CreatePullPointSubscriptionResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__tev__CreatePullPointSubscriptionResponse(soap, &tev__CreatePullPointSubscriptionResponse, "tev:CreatePullPointSubscriptionResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tev__GetEventProperties(struct soap *soap)
{	struct __tev__GetEventProperties soap_tmp___tev__GetEventProperties;
	struct _tev__GetEventPropertiesResponse tev__GetEventPropertiesResponse;
	soap_default__tev__GetEventPropertiesResponse(soap, &tev__GetEventPropertiesResponse);
	soap_default___tev__GetEventProperties(soap, &soap_tmp___tev__GetEventProperties);
	if (!soap_get___tev__GetEventProperties(soap, &soap_tmp___tev__GetEventProperties, "-tev:GetEventProperties", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tev__GetEventProperties(soap, soap_tmp___tev__GetEventProperties.tev__GetEventProperties, &tev__GetEventPropertiesResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize__tev__GetEventPropertiesResponse(soap, &tev__GetEventPropertiesResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__tev__GetEventPropertiesResponse(soap, &tev__GetEventPropertiesResponse, "tev:GetEventPropertiesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__tev__GetEventPropertiesResponse(soap, &tev__GetEventPropertiesResponse, "tev:GetEventPropertiesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tev__AddEventBroker(struct soap *soap)
{	struct __tev__AddEventBroker soap_tmp___tev__AddEventBroker;
	struct _tev__AddEventBrokerResponse tev__AddEventBrokerResponse;
	soap_default__tev__AddEventBrokerResponse(soap, &tev__AddEventBrokerResponse);
	soap_default___tev__AddEventBroker(soap, &soap_tmp___tev__AddEventBroker);
	if (!soap_get___tev__AddEventBroker(soap, &soap_tmp___tev__AddEventBroker, "-tev:AddEventBroker", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tev__AddEventBroker(soap, soap_tmp___tev__AddEventBroker.tev__AddEventBroker, &tev__AddEventBrokerResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize__tev__AddEventBrokerResponse(soap, &tev__AddEventBrokerResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__tev__AddEventBrokerResponse(soap, &tev__AddEventBrokerResponse, "tev:AddEventBrokerResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__tev__AddEventBrokerResponse(soap, &tev__AddEventBrokerResponse, "tev:AddEventBrokerResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tev__DeleteEventBroker(struct soap *soap)
{	struct __tev__DeleteEventBroker soap_tmp___tev__DeleteEventBroker;
	struct _tev__DeleteEventBrokerResponse tev__DeleteEventBrokerResponse;
	soap_default__tev__DeleteEventBrokerResponse(soap, &tev__DeleteEventBrokerResponse);
	soap_default___tev__DeleteEventBroker(soap, &soap_tmp___tev__DeleteEventBroker);
	if (!soap_get___tev__DeleteEventBroker(soap, &soap_tmp___tev__DeleteEventBroker, "-tev:DeleteEventBroker", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tev__DeleteEventBroker(soap, soap_tmp___tev__DeleteEventBroker.tev__DeleteEventBroker, &tev__DeleteEventBrokerResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize__tev__DeleteEventBrokerResponse(soap, &tev__DeleteEventBrokerResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__tev__DeleteEventBrokerResponse(soap, &tev__DeleteEventBrokerResponse, "tev:DeleteEventBrokerResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__tev__DeleteEventBrokerResponse(soap, &tev__DeleteEventBrokerResponse, "tev:DeleteEventBrokerResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tev__GetEventBrokers(struct soap *soap)
{	struct __tev__GetEventBrokers soap_tmp___tev__GetEventBrokers;
	struct _tev__GetEventBrokersResponse tev__GetEventBrokersResponse;
	soap_default__tev__GetEventBrokersResponse(soap, &tev__GetEventBrokersResponse);
	soap_default___tev__GetEventBrokers(soap, &soap_tmp___tev__GetEventBrokers);
	if (!soap_get___tev__GetEventBrokers(soap, &soap_tmp___tev__GetEventBrokers, "-tev:GetEventBrokers", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tev__GetEventBrokers(soap, soap_tmp___tev__GetEventBrokers.tev__GetEventBrokers, &tev__GetEventBrokersResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize__tev__GetEventBrokersResponse(soap, &tev__GetEventBrokersResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__tev__GetEventBrokersResponse(soap, &tev__GetEventBrokersResponse, "tev:GetEventBrokersResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__tev__GetEventBrokersResponse(soap, &tev__GetEventBrokersResponse, "tev:GetEventBrokersResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tev__Renew(struct soap *soap)
{	struct __tev__Renew soap_tmp___tev__Renew;
	struct _wsnt__RenewResponse wsnt__RenewResponse;
	soap_default__wsnt__RenewResponse(soap, &wsnt__RenewResponse);
	soap_default___tev__Renew(soap, &soap_tmp___tev__Renew);
	if (!soap_get___tev__Renew(soap, &soap_tmp___tev__Renew, "-tev:Renew", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tev__Renew(soap, soap_tmp___tev__Renew.wsnt__Renew, &wsnt__RenewResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize__wsnt__RenewResponse(soap, &wsnt__RenewResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__wsnt__RenewResponse(soap, &wsnt__RenewResponse, "wsnt:RenewResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__wsnt__RenewResponse(soap, &wsnt__RenewResponse, "wsnt:RenewResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tev__Unsubscribe_(struct soap *soap)
{	struct __tev__Unsubscribe_ soap_tmp___tev__Unsubscribe_;
	struct _wsnt__UnsubscribeResponse wsnt__UnsubscribeResponse;
	soap_default__wsnt__UnsubscribeResponse(soap, &wsnt__UnsubscribeResponse);
	soap_default___tev__Unsubscribe_(soap, &soap_tmp___tev__Unsubscribe_);
	if (!soap_get___tev__Unsubscribe_(soap, &soap_tmp___tev__Unsubscribe_, "-tev:Unsubscribe", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tev__Unsubscribe_(soap, soap_tmp___tev__Unsubscribe_.wsnt__Unsubscribe, &wsnt__UnsubscribeResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize__wsnt__UnsubscribeResponse(soap, &wsnt__UnsubscribeResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__wsnt__UnsubscribeResponse(soap, &wsnt__UnsubscribeResponse, "wsnt:UnsubscribeResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__wsnt__UnsubscribeResponse(soap, &wsnt__UnsubscribeResponse, "wsnt:UnsubscribeResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tev__Subscribe(struct soap *soap)
{	struct __tev__Subscribe soap_tmp___tev__Subscribe;
	struct _wsnt__SubscribeResponse wsnt__SubscribeResponse;
	soap_default__wsnt__SubscribeResponse(soap, &wsnt__SubscribeResponse);
	soap_default___tev__Subscribe(soap, &soap_tmp___tev__Subscribe);
	if (!soap_get___tev__Subscribe(soap, &soap_tmp___tev__Subscribe, "-tev:Subscribe", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tev__Subscribe(soap, soap_tmp___tev__Subscribe.wsnt__Subscribe, &wsnt__SubscribeResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize__wsnt__SubscribeResponse(soap, &wsnt__SubscribeResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__wsnt__SubscribeResponse(soap, &wsnt__SubscribeResponse, "wsnt:SubscribeResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__wsnt__SubscribeResponse(soap, &wsnt__SubscribeResponse, "wsnt:SubscribeResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tev__GetCurrentMessage(struct soap *soap)
{	struct __tev__GetCurrentMessage soap_tmp___tev__GetCurrentMessage;
	struct _wsnt__GetCurrentMessageResponse wsnt__GetCurrentMessageResponse;
	soap_default__wsnt__GetCurrentMessageResponse(soap, &wsnt__GetCurrentMessageResponse);
	soap_default___tev__GetCurrentMessage(soap, &soap_tmp___tev__GetCurrentMessage);
	if (!soap_get___tev__GetCurrentMessage(soap, &soap_tmp___tev__GetCurrentMessage, "-tev:GetCurrentMessage", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tev__GetCurrentMessage(soap, soap_tmp___tev__GetCurrentMessage.wsnt__GetCurrentMessage, &wsnt__GetCurrentMessageResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize__wsnt__GetCurrentMessageResponse(soap, &wsnt__GetCurrentMessageResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__wsnt__GetCurrentMessageResponse(soap, &wsnt__GetCurrentMessageResponse, "wsnt:GetCurrentMessageResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__wsnt__GetCurrentMessageResponse(soap, &wsnt__GetCurrentMessageResponse, "wsnt:GetCurrentMessageResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tev__Notify(struct soap *soap)
{	struct __tev__Notify soap_tmp___tev__Notify;
	soap_default___tev__Notify(soap, &soap_tmp___tev__Notify);
	if (!soap_get___tev__Notify(soap, &soap_tmp___tev__Notify, "-tev:Notify", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tev__Notify(soap, soap_tmp___tev__Notify.wsnt__Notify);
	if (soap->error)
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tev__GetMessages(struct soap *soap)
{	struct __tev__GetMessages soap_tmp___tev__GetMessages;
	struct _wsnt__GetMessagesResponse wsnt__GetMessagesResponse;
	soap_default__wsnt__GetMessagesResponse(soap, &wsnt__GetMessagesResponse);
	soap_default___tev__GetMessages(soap, &soap_tmp___tev__GetMessages);
	if (!soap_get___tev__GetMessages(soap, &soap_tmp___tev__GetMessages, "-tev:GetMessages", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tev__GetMessages(soap, soap_tmp___tev__GetMessages.wsnt__GetMessages, &wsnt__GetMessagesResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize__wsnt__GetMessagesResponse(soap, &wsnt__GetMessagesResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__wsnt__GetMessagesResponse(soap, &wsnt__GetMessagesResponse, "wsnt:GetMessagesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__wsnt__GetMessagesResponse(soap, &wsnt__GetMessagesResponse, "wsnt:GetMessagesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tev__DestroyPullPoint(struct soap *soap)
{	struct __tev__DestroyPullPoint soap_tmp___tev__DestroyPullPoint;
	struct _wsnt__DestroyPullPointResponse wsnt__DestroyPullPointResponse;
	soap_default__wsnt__DestroyPullPointResponse(soap, &wsnt__DestroyPullPointResponse);
	soap_default___tev__DestroyPullPoint(soap, &soap_tmp___tev__DestroyPullPoint);
	if (!soap_get___tev__DestroyPullPoint(soap, &soap_tmp___tev__DestroyPullPoint, "-tev:DestroyPullPoint", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tev__DestroyPullPoint(soap, soap_tmp___tev__DestroyPullPoint.wsnt__DestroyPullPoint, &wsnt__DestroyPullPointResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize__wsnt__DestroyPullPointResponse(soap, &wsnt__DestroyPullPointResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__wsnt__DestroyPullPointResponse(soap, &wsnt__DestroyPullPointResponse, "wsnt:DestroyPullPointResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__wsnt__DestroyPullPointResponse(soap, &wsnt__DestroyPullPointResponse, "wsnt:DestroyPullPointResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tev__Notify_(struct soap *soap)
{	struct __tev__Notify_ soap_tmp___tev__Notify_;
	soap_default___tev__Notify_(soap, &soap_tmp___tev__Notify_);
	if (!soap_get___tev__Notify_(soap, &soap_tmp___tev__Notify_, "-tev:Notify", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tev__Notify_(soap, soap_tmp___tev__Notify_.wsnt__Notify);
	if (soap->error)
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tev__CreatePullPoint(struct soap *soap)
{	struct __tev__CreatePullPoint soap_tmp___tev__CreatePullPoint;
	struct _wsnt__CreatePullPointResponse wsnt__CreatePullPointResponse;
	soap_default__wsnt__CreatePullPointResponse(soap, &wsnt__CreatePullPointResponse);
	soap_default___tev__CreatePullPoint(soap, &soap_tmp___tev__CreatePullPoint);
	if (!soap_get___tev__CreatePullPoint(soap, &soap_tmp___tev__CreatePullPoint, "-tev:CreatePullPoint", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tev__CreatePullPoint(soap, soap_tmp___tev__CreatePullPoint.wsnt__CreatePullPoint, &wsnt__CreatePullPointResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize__wsnt__CreatePullPointResponse(soap, &wsnt__CreatePullPointResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__wsnt__CreatePullPointResponse(soap, &wsnt__CreatePullPointResponse, "wsnt:CreatePullPointResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__wsnt__CreatePullPointResponse(soap, &wsnt__CreatePullPointResponse, "wsnt:CreatePullPointResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tev__Renew_(struct soap *soap)
{	struct __tev__Renew_ soap_tmp___tev__Renew_;
	struct _wsnt__RenewResponse wsnt__RenewResponse;
	soap_default__wsnt__RenewResponse(soap, &wsnt__RenewResponse);
	soap_default___tev__Renew_(soap, &soap_tmp___tev__Renew_);
	if (!soap_get___tev__Renew_(soap, &soap_tmp___tev__Renew_, "-tev:Renew", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tev__Renew_(soap, soap_tmp___tev__Renew_.wsnt__Renew, &wsnt__RenewResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize__wsnt__RenewResponse(soap, &wsnt__RenewResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__wsnt__RenewResponse(soap, &wsnt__RenewResponse, "wsnt:RenewResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__wsnt__RenewResponse(soap, &wsnt__RenewResponse, "wsnt:RenewResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tev__Unsubscribe__(struct soap *soap)
{	struct __tev__Unsubscribe__ soap_tmp___tev__Unsubscribe__;
	struct _wsnt__UnsubscribeResponse wsnt__UnsubscribeResponse;
	soap_default__wsnt__UnsubscribeResponse(soap, &wsnt__UnsubscribeResponse);
	soap_default___tev__Unsubscribe__(soap, &soap_tmp___tev__Unsubscribe__);
	if (!soap_get___tev__Unsubscribe__(soap, &soap_tmp___tev__Unsubscribe__, "-tev:Unsubscribe", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tev__Unsubscribe__(soap, soap_tmp___tev__Unsubscribe__.wsnt__Unsubscribe, &wsnt__UnsubscribeResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize__wsnt__UnsubscribeResponse(soap, &wsnt__UnsubscribeResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__wsnt__UnsubscribeResponse(soap, &wsnt__UnsubscribeResponse, "wsnt:UnsubscribeResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__wsnt__UnsubscribeResponse(soap, &wsnt__UnsubscribeResponse, "wsnt:UnsubscribeResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tev__PauseSubscription(struct soap *soap)
{	struct __tev__PauseSubscription soap_tmp___tev__PauseSubscription;
	struct _wsnt__PauseSubscriptionResponse wsnt__PauseSubscriptionResponse;
	soap_default__wsnt__PauseSubscriptionResponse(soap, &wsnt__PauseSubscriptionResponse);
	soap_default___tev__PauseSubscription(soap, &soap_tmp___tev__PauseSubscription);
	if (!soap_get___tev__PauseSubscription(soap, &soap_tmp___tev__PauseSubscription, "-tev:PauseSubscription", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tev__PauseSubscription(soap, soap_tmp___tev__PauseSubscription.wsnt__PauseSubscription, &wsnt__PauseSubscriptionResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize__wsnt__PauseSubscriptionResponse(soap, &wsnt__PauseSubscriptionResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__wsnt__PauseSubscriptionResponse(soap, &wsnt__PauseSubscriptionResponse, "wsnt:PauseSubscriptionResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__wsnt__PauseSubscriptionResponse(soap, &wsnt__PauseSubscriptionResponse, "wsnt:PauseSubscriptionResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tev__ResumeSubscription(struct soap *soap)
{	struct __tev__ResumeSubscription soap_tmp___tev__ResumeSubscription;
	struct _wsnt__ResumeSubscriptionResponse wsnt__ResumeSubscriptionResponse;
	soap_default__wsnt__ResumeSubscriptionResponse(soap, &wsnt__ResumeSubscriptionResponse);
	soap_default___tev__ResumeSubscription(soap, &soap_tmp___tev__ResumeSubscription);
	if (!soap_get___tev__ResumeSubscription(soap, &soap_tmp___tev__ResumeSubscription, "-tev:ResumeSubscription", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tev__ResumeSubscription(soap, soap_tmp___tev__ResumeSubscription.wsnt__ResumeSubscription, &wsnt__ResumeSubscriptionResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize__wsnt__ResumeSubscriptionResponse(soap, &wsnt__ResumeSubscriptionResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__wsnt__ResumeSubscriptionResponse(soap, &wsnt__ResumeSubscriptionResponse, "wsnt:ResumeSubscriptionResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__wsnt__ResumeSubscriptionResponse(soap, &wsnt__ResumeSubscriptionResponse, "wsnt:ResumeSubscriptionResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.c */
